#!/usr/bin/env bash

NAME="vtl"
VERSION="latest"

echo
echo
echo "... docker .................................................."
echo "............................................................."
echo

docker build --no-cache -t ulisesjeremias/$NAME:$VERSION . --build-arg VTL_VERSION=$VERSION
docker images -q -f "dangling=true" | xargs docker rmi
